#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 att32.nasm
gcc -m32 -msse -O0 -no-pie sseutils32.o att32.o att32c.c -o att32c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./att32c $pars
