#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 att32omp.nasm
gcc -m32 -msse -O0 -no-pie -fopenmp sseutils32.o att32omp.o att32comp.c -o att32omp -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./att32comp $pars
