#!/bin/bash
if [[ ! -e sseutils64.o ]]; then nasm -f elf64 sseutils64.nasm; fi;
nasm -f elf64 att64.nasm
gcc -m64 -msse -mavx -O0 -no-pie sseutils64.o att64.o att64c.c -o att64c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./att64c $pars
